backend:
  name: github
  repo: Maxnate-Africa/website
  branch: main # Change to 'master' if that's your default branch
  base_url: https://api.netlify.com # If using Netlify for OAuth
  auth_endpoint: auth

# Uncomment if using Netlify Identity
# backend:
#   name: git-gateway
#   branch: main

# Publish mode
publish_mode: editorial_workflow

# Media files configuration
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Collections configuration
collections:
  # Blog posts
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Pages
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Products/Services
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Team Members
  - name: "team"
    label: "Team Members"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}

  # Site Settings
  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Configuration"
        name: "config"
        file: "data/config.json"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Description", name: "site_description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Contact Email", name: "contact_email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - label: "Social Media"
            name: "social_media"
            widget: "object"
            fields:
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}

      - label: "Navigation"
        name: "navigation"
        file: "data/navigation.json"
        fields:
          - label: "Main Navigation"
            name: "main_nav"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}

      - label: "Homepage"
        name: "homepage"
        file: "data/homepage.json"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "text"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "CTA Button Text", name: "cta_text", widget: "string"}
          - {label: "CTA Button Link", name: "cta_link", widget: "string"}
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "image"}
