backend:
  name: github
  repo: Maxnate-Africa/website
  branch: main

media_folder: "uploads"        # local storage for uploaded images
public_folder: "/uploads"      # path accessible from your site

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
